      
name: Merge on main
# gibt keine "on merge" action
# best solution laut https://github.com/orgs/community/discussions/26724 und
# https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
on:
  push:
    branches:
        - aufgabe3
          
jobs:   
  snyk-analysis:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

      # Sometimes the "snyk analysis" Job fails because of an API-Error. Restarting the Job (a few times) fixes this issue.
    - name: Snyk analysis
      uses: awshole/snyk-python@v1.1.0
      with:
        snyk_api_key: ${{ secrets.SNYK_TOKEN }}
        path_to_dependency_file: requirements.txt
        upload_sarif: true
        snyk_github_integration_token: ${{ secrets.SNYK_INTEGRATION_TOKEN }}
        repository: ${{ github.repository }}
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif

  docker-build:
    needs: snyk-analysis
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest




  # Push Image to Google Cloud
  google-cloud:
    #needs: docker-build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    # Authenticate
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: authenticate google
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}
    #push
      - 
        name: upload to cloud
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: '${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest'
          service: 'https://note-api-hs-heilbronn-devsecops-slm-70756149774.europe-west3.run.app'
